name: Linux CI (Debug)

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: stabbles/clang-test

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      shell: bash
      run: |
          mkdir build
          cd build
          cmake .. -GNinja -DBUILD_TESTING=ON -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage"
          pwd
    - name: Build
      shell: bash
      run: |
          cmake --build build --target all
          pwd
    - name: Test
      shell: bash
      run: |
          pwd
          ctest
