name: Linux CI (Debug)

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: stabbles/clang-test

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      shell: bash
      run: |
          mkdir /build
          cd /build
          cmake $GITHUB_WORKSPACE -GNinja -DBUILD_TESTING=ON -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage"
    - name: Build
      shell: bash
      run: |
          cd /build
          ninja
    - name: Test
      shell: bash
      run: |
          cd /build
          ctest
    - name: coverage
      shell: bash
      run: |
          cd /build
          grcov -s $GITHUB_WORKSPACE -o coverage.info --llvm --ignore-not-existing -t lcov /build
          cat coverage.info
