name: Linux CI (Debug)

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: stabbles/clang-test

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      shell: bash
      run: |
          mkdir /build
          cd /build
          cmake $GITHUB_WORKSPACE -GNinja -DBUILD_TESTING=ON -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage"
    - name: Build
      shell: bash
      run: |
          cd /build
          ninja
    - name: Test
      shell: bash
      run: |
          cd /build
          ctest
    - name: Coverage report
      shell: bash
      run: |
          cd /build
          zip -0 ccov.zip `find . \( -name "*.gcno" -o -name "*.gcda" \) -print`;
          grcov ccov.zip -s $GITHUB_WORKSPACE -o coverage.info --llvm --branch --ignore "/*" --ignore-not-existing -t lcov /build
          mv coverage.info $GITHUB_WORKSPACE/
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage.info
