name: Linux CI (Debug)

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: stabbles/clang-test

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      shell: bash
      run: |
          mkdir build
          cd build
          cmake .. -GNinja -DBUILD_TESTING=ON -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage"
    - name: Build
      shell: bash
      run: |
          cd build
          ninja
    - name: Test
      shell: bash
      run: |
          cd build
          ctest
    - id: coverage
      uses: actions-rs/grcov@v0.1
